server.port=0

stats-service-id=stats-server

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://event-db:5432/ewm-event
spring.datasource.username=event
spring.datasource.password=event

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-event.sql