services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - POSTGRES_DB=ewm-stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data/
      - ./stat/stat-server/src/main/resources/schema-stat.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stat -d ewm-stats"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  stats-server:
    build: stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    restart: on-failure

  user-db:
    image: postgres:16.1
    container_name: postgres-ewm-user-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=ewm-user
    volumes:
      - user-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ewm-user"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  event-db:
    image: postgres:16.1
    container_name: postgres-ewm-event-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=event
      - POSTGRES_PASSWORD=event
      - POSTGRES_DB=ewm-event
    volumes:
      - event-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event -d ewm-event"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  request-db:
    image: postgres:16.1
    container_name: postgres-ewm-request-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_USER=request
      - POSTGRES_PASSWORD=request
      - POSTGRES_DB=ewm-request
    volumes:
      - request-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U request -d ewm-request"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  review-db:
    image: postgres:16.1
    container_name: postgres-ewm-review-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_USER=review
      - POSTGRES_PASSWORD=review
      - POSTGRES_DB=ewm-review
    volumes:
      - review-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U review -d ewm-review"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

volumes:
  stats-db-data:
  user-db-data:
  event-db-data:
  request-db-data:
  review-db-data: