CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(500) NOT NULL,
    comment_id BIGINT,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_comments_parent
        FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
    CONSTRAINT chk_comments_ids CHECK (id != comment_id)
);

CREATE INDEX IF NOT EXISTS idx_comments_event_author_date
    ON comments(event_id, author_id, creation_date ASC);

CREATE INDEX IF NOT EXISTS idx_comments_comment_id
    ON comments(comment_id);